version: "3.3"
services:
  bot:
    extends:
      file: ./app/bot/docker-compose.yml
      service: bot
    depends_on:
      - db
    networks:
      - net
  redis:
    extends:
      file: ./app/bot/docker-compose.yml
      service: redis
    ports:
      - '6379:6379'
    networks:
      - net
  db:
    image: postgres:15.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSWD}
      - POSTGRES_DB=${DB_DB}
    ports:
      - '5436:${DB_PORT}'
    networks:
      - net
    volumes: 
      - db:/var/lib/postgresql/data

  back:
    extends:
      file: ./app/back/docker-compose.yml
      service: back
    depends_on:
      - db
    networks:
      - net

volumes:
  db:
  venvs:
  redis_data:
    driver_opts:
      type: none
      o: bind
      device: /home/bot/redis_data

networks:
  net:
    driver: bridge