"""add_products

Revision ID: 115f77598f32
Revises: c2ca94db76be
Create Date: 2025-01-19 09:23:36.528242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115f77598f32'
down_revision = 'c2ca94db76be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey')),
    sa.UniqueConstraint('name', name=op.f('products_name_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
