"""add_orders_and_statuses

Revision ID: ed804436c9ac
Revises: e32c4f58a6e2
Create Date: 2025-01-19 11:28:17.542475

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed804436c9ac"
down_revision = "e32c4f58a6e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("order_statuses_pkey")),
        sa.UniqueConstraint("name", name=op.f("order_statuses_name_key")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("delivery_method_id", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_method_id"],
            ["delivery_methods.id"],
            name=op.f("orders_delivery_method_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["order_statuses.id"], name=op.f("orders_status_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("order_statuses")
    # ### end Alembic commands ###
