"""add_delivery_method

Revision ID: e32c4f58a6e2
Revises: 951b031525b7
Create Date: 2025-01-19 11:00:22.247540

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e32c4f58a6e2"
down_revision = "951b031525b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_methods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("delivery_methods_pkey")),
        sa.UniqueConstraint("name", name=op.f("delivery_methods_name_key")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery_methods")
    # ### end Alembic commands ###
